#ifndef _ROSLOGGING_H_
#define _ROSLOGGING_H_ 1

//
// Copyright (C) Microsoft. All rights reserved.
//
// WPP tracing configuration file shared between usermode and kernel mode.
//

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

//
// Debug/Bugcheck helpers used by tracing macros.
// NOTE: These are not intended to be called from anywhere else
//
extern int _RosLogBugcheck (ULONG Level);
extern int _RosLogDebug (ULONG Level);
    
// begin_wpp config
//
// FUNC ROS_LOG_CRITICAL_ERROR{LEVEL=TRACE_LEVEL_CRITICAL, FLAGS=ROS_TRACING_BUGCHECK}(MSG, ...);
// USEPREFIX (ROS_LOG_CRITICAL_ERROR, "%!STDPREFIX! [%s @ %u] CRITICAL ERROR:", __FILE__, __LINE__);
//
// FUNC ROS_LOG_ASSERTION{LEVEL=TRACE_LEVEL_ERROR, FLAGS=ROS_TRACING_DEBUG}(MSG, ...);
// USEPREFIX (ROS_LOG_ASSERTION, "%!STDPREFIX! [%s @ %u] ASSERTION :", __FILE__, __LINE__);
//
// FUNC ROS_LOG_ERROR{LEVEL=TRACE_LEVEL_ERROR, FLAGS=ROS_TRACING_DEFAULT}(MSG, ...);
// USEPREFIX (ROS_LOG_ERROR, "%!STDPREFIX! [%s @ %u] ERROR :", __FILE__, __LINE__);
//
// FUNC ROS_LOG_LOW_MEMORY{LEVEL=TRACE_LEVEL_ERROR, FLAGS=ROS_TRACING_DEFAULT}(MSG, ...);
// USEPREFIX (ROS_LOG_LOW_MEMORY, "%!STDPREFIX! [%s @ %u] LOW MEMORY :", __FILE__, __LINE__);
//
// FUNC ROS_LOG_WARNING{LEVEL=TRACE_LEVEL_WARNING, FLAGS=ROS_TRACING_DEFAULT}(MSG, ...);
// USEPREFIX (ROS_LOG_WARNING, "%!STDPREFIX! [%s @ %u] WARNING :", __FILE__, __LINE__);
//
// FUNC ROS_LOG_INFORMATION{LEVEL=TRACE_LEVEL_INFORMATION, FLAGS=ROS_TRACING_DEFAULT}(MSG, ...);
// USEPREFIX (ROS_LOG_INFORMATION, "%!STDPREFIX! [%s @ %u] INFO :", __FILE__, __LINE__);
//
// FUNC ROS_LOG_TRACE{LEVEL=TRACE_LEVEL_VERBOSE, FLAGS=ROS_TRACING_DEFAULT}(MSG, ...);
// USEPREFIX (ROS_LOG_TRACE, "%!STDPREFIX! [%s @ %u] TRACE :", __FILE__, __LINE__);
//
// FUNC ROS_TRACE_EVENTS(LEVEL, FLAGS, MSG, ...);
// USEPREFIX (ROS_TRACE_EVENTS, "%!STDPREFIX! [%s @ %u] TRACE :", __FILE__, __LINE__);
//
// FUNC ROS_CRITICAL_ASSERT{LEVEL=TRACE_LEVEL_CRITICAL, FLAGS=ROS_TRACING_BUGCHECK}(ROS_CRIT_ASSERT_EXP);
// USEPREFIX (ROS_CRITICAL_ASSERT, "%!STDPREFIX! [%s @ %u] CRITICAL ASSERTION :%s", __FILE__, __LINE__, #ROS_CRIT_ASSERT_EXP);
//
// FUNC ROS_ASSERT{LEVEL=TRACE_LEVEL_ERROR, FLAGS=ROS_TRACING_DEBUG}(ROS_ASSERT_EXP);
// USEPREFIX (ROS_ASSERT, "%!STDPREFIX! [%s @ %u] ASSERTION :%s", __FILE__, __LINE__, #ROS_ASSERT_EXP);
//
// end_wpp


//
// ROS_LOG... customization
//

#define WPP_LEVEL_FLAGS_POST(LEVEL,FLAGS) \
    ,(((WPP_BIT_ ## FLAGS) == WPP_BIT_ROS_TRACING_BUGCHECK) ? \
            _RosLogBugcheck(LEVEL) : \
            (((WPP_BIT_ ## FLAGS) == WPP_BIT_ROS_TRACING_DEBUG) ? \
                _RosLogDebug(LEVEL) : 1))

//
// ROS_CRTITICAL_ASSERT customization
//

#define WPP_RECORDER_LEVEL_FLAGS_ROS_CRIT_ASSERT_EXP_FILTER(LEVEL, FLAGS, ROS_CRIT_ASSERT_EXP) \
    (!(ROS_CRIT_ASSERT_EXP))

#define WPP_RECORDER_LEVEL_FLAGS_ROS_CRIT_ASSERT_EXP_ARGS(LEVEL, FLAGS, ROS_CRIT_ASSERT_EXP) \
    WPP_CONTROL(WPP_BIT_ ## FLAGS).AutoLogContext, LEVEL, WPP_BIT_ ## FLAGS

#define WPP_LEVEL_FLAGS_ROS_CRIT_ASSERT_EXP_POST(LEVEL, FLAGS, ROS_CRIT_ASSERT_EXP) \
    ,((!(ROS_CRIT_ASSERT_EXP)) ? _RosLogBugcheck(LEVEL) : 1)

//
// ROS_ASSERT customization
//

#define WPP_RECORDER_LEVEL_FLAGS_ROS_ASSERT_EXP_FILTER(LEVEL, FLAGS, ROS_ASSERT_EXP) \
    (!(ROS_ASSERT_EXP))

#define WPP_RECORDER_LEVEL_FLAGS_ROS_ASSERT_EXP_ARGS(LEVEL, FLAGS, ROS_ASSERT_EXP) \
    WPP_CONTROL(WPP_BIT_ ## FLAGS).AutoLogContext, LEVEL, WPP_BIT_ ## FLAGS

#define WPP_LEVEL_FLAGS_ROS_ASSERT_EXP_POST(LEVEL, FLAGS, ROS_ASSERT_EXP) \
    ,((!(ROS_ASSERT_EXP)) ? _RosLogDebug(LEVEL) : 1)


#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif // _ROSLOGGING_H_

