#ifndef _GPIOHPDLOGGING_H_
#define _GPIOHPDLOGGING_H_ 1

//
// Copyright (C) Microsoft. All rights reserved.
//

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

//
// Defining control guids, including this is required to happen before
// including the tmh file (if the WppRecorder API is used)
//
#include <WppRecorder.h>

//
// Tracing GUID - F1876EBA-DE5A-4990-9A53-7B52CDEF08DA
//
#define WPP_CONTROL_GUIDS \
    WPP_DEFINE_CONTROL_GUID(GPIOHPD, (F1876EBA,DE5A,4990,9A53,7B52CDEF08DA), \
        WPP_DEFINE_BIT(GPIOHPD_TRACING_DEFAULT) \
        WPP_DEFINE_BIT(GPIOHPD_TRACING_DEBUG) \
        WPP_DEFINE_BIT(GPIOHPD_TRACING_BUGCHECK) \
    )

// begin_wpp config
//
// FUNC GPIOHPD_LOG_ASSERTION{LEVEL=TRACE_LEVEL_ERROR, FLAGS=GPIOHPD_TRACING_DEBUG}(MSG, ...);
// USEPREFIX (GPIOHPD_LOG_ASSERTION, "%!STDPREFIX! [%s @ %u] ASSERTION :", __FILE__, __LINE__);
//
// FUNC GPIOHPD_LOG_ERROR{LEVEL=TRACE_LEVEL_ERROR, FLAGS=GPIOHPD_TRACING_DEFAULT}(MSG, ...);
// USEPREFIX (GPIOHPD_LOG_ERROR, "%!STDPREFIX! [%s @ %u] ERROR :", __FILE__, __LINE__);
//
// FUNC GPIOHPD_LOG_LOW_MEMORY{LEVEL=TRACE_LEVEL_ERROR, FLAGS=GPIOHPD_TRACING_DEFAULT}(MSG, ...);
// USEPREFIX (GPIOHPD_LOG_LOW_MEMORY, "%!STDPREFIX! [%s @ %u] LOW MEMORY :", __FILE__, __LINE__);
//
// FUNC GPIOHPD_LOG_WARNING{LEVEL=TRACE_LEVEL_WARNING, FLAGS=GPIOHPD_TRACING_DEFAULT}(MSG, ...);
// USEPREFIX (GPIOHPD_LOG_WARNING, "%!STDPREFIX! [%s @ %u] WARNING :", __FILE__, __LINE__);
//
// FUNC GPIOHPD_LOG_INFORMATION{LEVEL=TRACE_LEVEL_INFORMATION, FLAGS=GPIOHPD_TRACING_DEFAULT}(MSG, ...);
// USEPREFIX (GPIOHPD_LOG_INFORMATION, "%!STDPREFIX! [%s @ %u] INFO :", __FILE__, __LINE__);
//
// FUNC GPIOHPD_LOG_TRACE{LEVEL=TRACE_LEVEL_VERBOSE, FLAGS=GPIOHPD_TRACING_DEFAULT}(MSG, ...);
// USEPREFIX (GPIOHPD_LOG_TRACE, "%!STDPREFIX! [%s @ %u] TRACE :", __FILE__, __LINE__);
//
// end_wpp

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif // _GPIOHPDLOGGING_H_

